### ISSUE TITLE
Problem to work

### ISSUE THREAD

**Issue by cmaxxx** [ConfusedCharacter/NotCoin-Cheat#10]
I Get Error After Login
`Traceback (most recent call last):
  File "/root/not2.py", line 135, in <module>
    hashes = send_result['data'][0]['hash']
TypeError: 'NoneType' object is not subscriptable`

**Comment by THMaST3R** [comment]
i have same error(after update to the latest version)

```
Traceback (most recent call last):
  File "/root/NotCoin-Cheat/NotCoin.py", line 135, in <module>
    hashes = send_result['data'][0]['hash']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by soshin1337** [comment]
![image](https://github.com/ConfusedCharacter/NotCoin-Cheat/assets/15040527/42e318cc-24cd-4aa6-aac2-92f6fad4c5a6)

this problem occurs due to captcha from cloudflare

**Comment by ConfusedCharacter** [comment]
This problem is related to Cloudflare's anti-bot measures. I'm trying to solve it. If anyone has knowledge about bypass and can help me, please do.

**Comment by soshin1337** [comment]
> This problem is related to Cloudflare's anti-bot measures. I'm trying to solve it. If anyone has knowledge about bypass and can help me, please do.

https://www.zenrows.com/blog/bypass-cloudflare-python check this

**Comment by ConfusedCharacter** [comment]
> > This problem is related to Cloudflare's anti-bot measures. I'm trying to solve it. If anyone has knowledge about bypass and can help me, please do.
> 
> https://www.zenrows.com/blog/bypass-cloudflare-python check this

i tried all of these last night and not works😀

**Comment by soshin1337** [comment]
> > > This problem is related to Cloudflare's anti-bot measures. I'm trying to solve it. If anyone has knowledge about bypass and can help me, please do.
> > 
> > 
> > https://www.zenrows.com/blog/bypass-cloudflare-python check this
> 
> i tried all of these last night and not works😀

no ideas yet 🙁

**Comment by soshin1337** [comment]
fixed

**Comment by ConfusedCharacter** [comment]
check new update.

**Comment by cmaxxx** [comment]
> This problem is related to Cloudflare's anti-bot measures. I'm trying to solve it. If anyone has knowledge about bypass and can help me, please do.

Use this
https://2captcha.com/api-docs/cloudflare-turnstile

You need to pay a fee, but it is very cheap
