### ISSUE TITLE
ban shodam :|

### ISSUE THREAD

**Issue by AboliOneStar** [ConfusedCharacter/NotCoin-Cheat#4]
may fakin ekant ban shodinge ...

**Comment by ConfusedCharacter** [comment]
maybe you should change the range of collect . notcoin can't detect this script. i using my self

**Comment by AboliOneStar** [comment]
My Telegram account has been deleted and blocked.

**Comment by ConfusedCharacter** [comment]
no one reports issues like this until yet and i don't think this script causes telegram tos and rules, this script getting just authorization with your account.
