### ISSUE TITLE
It does not form like before

### ISSUE THREAD

**Issue by THMaST3R** [ConfusedCharacter/NotCoin-Cheat#7]
Hello, until yesterday it was working very well, but today it is not working properly at all
yesterday: 20k coin per hour
today: maybe 5k

**Comment by ConfusedCharacter** [comment]
write the errors for me and say do you see "eval result" error?

**Comment by THMaST3R** [comment]
i dont get an error
just this
```
Session Expired Getting new session
```

**Comment by ConfusedCharacter** [comment]
seesion expired is ok, after execution, do you check how much is the source of NotCoin and whether it is below 500 or not? If it is below 500, this mean is collecting and there is no problem because the coins are charged after some time

**Comment by THMaST3R** [comment]
Yes, I checked it and it was +5500

**Comment by ConfusedCharacter** [comment]
works fine i test it

**Comment by ConfusedCharacter** [comment]
script now updated, use latest.
