### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by THMaST3R** [ConfusedCharacter/NotCoin-Cheat#9]
i use latest version but ...

```
Traceback (most recent call last):
  File "/root/NotCoin-Cheat/NotCoin.py", line 96, in <module>
    hashes = send_result['data'][0]['hash']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by ConfusedCharacter** [comment]
> bypass Cloudflare's anti-bot scraper = cloudscraper.create_scraper() If you already have an existing Requests session, you can pass it to the function create_scraper() to continue using that session. session = requests.session() scraper = cloudscraper.create_scraper(sess=session)

The problem is from another place, I am trying to solve it

**Comment by ConfusedCharacter** [comment]
> bypass Cloudflare's anti-bot scraper = cloudscraper.create_scraper() If you already have an existing Requests session, you can pass it to the function create_scraper() to continue using that session. session = requests.session() scraper = cloudscraper.create_scraper(sess=session)

tnx man your comment helps me to fix new problem

**Comment by ConfusedCharacter** [comment]
> i use latest version but ...
> 
> ```
> Traceback (most recent call last):
>   File "/root/NotCoin-Cheat/NotCoin.py", line 96, in <module>
>     hashes = send_result['data'][0]['hash']
> TypeError: 'NoneType' object is not subscriptable
> ```

script updated , now use latest. tnx for report.

**Comment by ConfusedCharacter** [comment]
> bypass Cloudflare's anti-bot scraper = cloudscraper.create_scraper() If you already have an existing Requests session, you can pass it to the function create_scraper() to continue using that session. session = requests.session() scraper = cloudscraper.create_scraper(sess=session)

thanks for your help.

**Comment by tawanaproxy** [comment]
i use last verion but i have errore 


collect coins: 16 with hash -1
Traceback (most recent call last):
  File "/root/t1/NotCoin-Cheat/NotCoin.py", line 135, in <module>
    hashes = send_result['data'][0]['hash']
TypeError: 'NoneType' object is not subscriptable

**Comment by ConfusedCharacter** [comment]
i test the script and works fine, use vpn.

**Comment by soshin1337** [comment]
> i use last verion but i have errore
> 
> collect coins: 16 with hash -1 Traceback (most recent call last): File "/root/t1/NotCoin-Cheat/NotCoin.py", line 135, in hashes = send_result['data'][0]['hash'] TypeError: 'NoneType' object is not subscriptable

same problem
